use UNIVER;
SELECT PULPIT.PULPIT_NAME,FACULTY.FACULTY
FROM FACULTY,PULPIT
Where PULPIT.FACULTY=FACULTY.FACULTY
and  PULPIT.FACULTY In (SELECT FACULTY FROM PROFESSION Where (PROFESSION_NAME Like'%технологии%' or PROFESSION_NAME Like'%технология%'))
SELECT PULPIT.PULPIT_NAME,FACULTY.FACULTY
FROM FACULTY Inner Join PULPIT
On PULPIT.FACULTY=FACULTY.FACULTY
and  PULPIT.FACULTY In (SELECT FACULTY FROM PROFESSION Where (PROFESSION_NAME Like'%технологии%' or PROFESSION_NAME Like'%технология%'))
SELECT DISTINCT PULPIT.PULPIT_NAME,FACULTY.FACULTY
FROM FACULTY Inner Join PULPIT
On PULPIT.FACULTY=FACULTY.FACULTY
Inner Join PROFESSION
On FACULTY.FACULTY=PROFESSION.FACULTY
Where (PROFESSION_NAME Like'%технологии%' or PROFESSION_NAME Like'%технология%')
SELECT  a.AUDITORIUM_CAPACITY, a.AUDITORIUM_TYPE
FROM AUDITORIUM a
Where AUDITORIUM_CAPACITY=(SELECT top(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa Where a.AUDITORIUM_TYPE=aa.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)
SELECT FACULTY_NAME FROM FACULTY
WHERE not exists (SELECT * FROM PULPIT
WHERE PULPIT.FACULTY=FACULTY.FACULTY)
SELECT top 1
(SELECT AVG(NOTE) from PROGRESS
Where SUBJECT Like '%ОАиП%')[ОАиП],
(SELECT AVG(NOTE) from PROGRESS
Where SUBJECT Like '%БД%')[БД],
(SELECT AVG(NOTE) from PROGRESS
Where SUBJECT Like '%СУБД%')[СУБД]
FROM PROGRESS
SELECT NOTE, SUBJECT FROM PROGRESS
WHERE NOTE>=all (select NOTE FROM PROGRESS WHERE SUBJECT like 'О%')
SELECT NOTE, SUBJECT FROM PROGRESS
WHERE NOTE>any (select NOTE FROM PROGRESS WHERE SUBJECT like 'О%')
