use UNIVER;
SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY ROLLUP(FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)
--2
SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY CUBE(FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)
--3
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION
 SELECT  GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '’“Ë“')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
--4
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION ALL
 SELECT  GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '’“Ë“')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
--5
SELECT  GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
INTERSECT
 SELECT  GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '’“Ë“')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
--6
SELECT  GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '»ƒËœ')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT
EXCEPT
 SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( '’“Ë“')
GROUP BY GROUPS.PROFESSION,PROGRESS.SUBJECT