use UNIVER;
SELECT AUDITORIUM.AUDITORIUM_TYPE,
max(AUDITORIUM_CAPACITY)[максимальную вместимость аудиторий],
min (AUDITORIUM_CAPACITY)[минимальную вместимость аудиторий],
avg (AUDITORIUM_CAPACITY)[средняя вместимость аудиторий],
SUM(AUDITORIUM_CAPACITY)[суммарную вместимость всех аудиторий ],
count(*)[общее количество аудиторий данного типа]
From AUDITORIUM INNER JOIN AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE Group By AUDITORIUM.AUDITORIUM_TYPE
SELECT *
FROM (SELECT Case when NOTE between 4 and 6 then 'оценка>4'
when NOTE between 6 and 8 then 'оценка>6'
else 'оценка>8'
end [Интервалы оценок],count(*)[Количество]
From PROGRESS GROUP BY Case
 when NOTE between 4 and 6 then 'оценка>4'
when NOTE between 6 and 8 then 'оценка>6'
else 'оценка>8'
end ) as T
order by Case[Интервалы оценок]
when 'оценка>4' then 3
when 'оценка>6' then 2
when 'оценка>8' then 1
else 0
end
SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.NOTE,
ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.NOTE

SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT , PROGRESS.NOTE,
ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE PROGRESS.SUBJECT IN( 'БД','ОАиП')
GROUP BY  FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT , PROGRESS.NOTE

SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT ,  
ROUND(AVG(CAST(PROGRESS.NOTE as float)),2) AS AVERAGE_NOTE
From FACULTY INNER JOIN GROUPS 
On FACULTY.FACULTY = GROUPS.FACULTY INNER JOIN STUDENT 
ON GROUPS.IDGROUP= STUDENT.IDGROUP 
inner join PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN( 'ИДиП')
GROUP BY  FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

SELECT t1.SUBJECT , t1.NOTE,
(select count(*) from PROGRESS t2 
where t1.SUBJECT = t2.SUBJECT  AND t1.NOTE = t2.NOTE)[Количество]
FROM PROGRESS t1 
GROUP BY t1.SUBJECT , t1.NOTE
HAVING NOTE = 8 OR NOTE =9 