use UNIVER;
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE  Inner Join AUDITORIUM
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE  Inner Join AUDITORIUM
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE And  AUDITORIUM_TYPE.AUDITORIUM_TYPE LIKE '%компьютер%';
SELECT 
    FACULTY.FACULTY_NAME AS Факультет,
    PULPIT.PULPIT_NAME AS Кафедра,
    GROUPS.PROFESSION AS Специальность,
    SUBJECT.SUBJECT_NAME AS Дисциплина,
    STUDENT.NAME AS Имя_Студента,
    CASE 
        WHEN PROGRESS.NOTE = 6 THEN 'шесть'
        WHEN PROGRESS.NOTE = 7 THEN 'семь'
        WHEN PROGRESS.NOTE = 8 THEN 'восемь'
    END AS Оценка
FROM 
    PROGRESS
INNER JOIN 
    STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN 
    GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN 
    SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN 
    PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN 
    FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE 
    PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY 
    PROGRESS.NOTE DESC;
SELECT 
    PULPIT.PULPIT_NAME AS Кафедра,
    ISNULL(TEACHER.TEACHER_NAME, '***') AS Преподаватель
FROM 
    PULPIT
LEFT OUTER JOIN 
    TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT
ORDER BY 
    PULPIT.PULPIT_NAME;
SELECT * FROM STUDENT FULL Join GROUPS
On STUDENT.IDGROUP= GROUPS.IDGROUP
SELECT * FROM STUDENT FULL Join GROUPS
On STUDENT.IDGROUP= GROUPS.IDGROUP Where STUDENT.INFO is not null;
SELECT * FROM STUDENT FULL Join GROUPS
On STUDENT.IDGROUP= GROUPS.IDGROUP Where GROUPS.YEAR_FIRST is null;
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE  Cross Join AUDITORIUM
Where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;